### ISSUE TITLE
Make ProjectOnGroup a template

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#7]
In Grid/tensors/Tensor_Ta.h, ProjectOnGroup should probably be a template. We need to figure out the consequences and find a nice, least intrusive way to separate out the implementation from the interface. We should keep an eye on how such change affects other parts of the code.

**Comment by LupoA** [comment]
Summing up what I came up with: if done in GaugeGroup.h calling to the functions in Tensor_Ta.h there are two options I can see

1. having a non-void function to return the projected value. This seems against the philosophy of the SU and Sp classes where all function are static void 
2. having ProjectOnGroup(in,out) avoids returning, but across the code ProjectOnGroup has to be modified to take two arguments instead of one 

If done directly in Tensor_Ta.h

3. I would like to use function overloading (since I learnt that partial specialisation is not possible) but tensors knows nothing about groups. Maybe we could use type traits, or something similar to #14
